package org.fluxgate.spring.reload.strategy;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import org.fluxgate.core.reload.ReloadSource;
import org.fluxgate.core.reload.RuleReloadEvent;
import org.fluxgate.core.reload.RuleReloadListener;
import org.fluxgate.core.reload.RuleReloadStrategy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Abstract base class for reload strategies.
 *
 * <p>Provides common functionality for managing listeners and lifecycle state.
 *
 * <p><b>Listener ordering is part of the contract.</b> Listeners are notified in ascending order
 * (lowest first), so cache invalidation always runs before bucket reset - the reverse order would
 * let an in-flight request recreate a bucket from the stale rule after the reset. The starter
 * registers {@code CachingRuleSetProvider} at {@link #ORDER_CACHE_INVALIDATION} and the bucket
 * reset handler at {@link #ORDER_BUCKET_RESET}; {@link #addListener(RuleReloadListener)} defaults
 * to {@code 0}, in between.
 *
 * <p>If a listener fails, every listener with a strictly higher order is skipped for that event:
 * resetting buckets while the rules behind them are still stale would silently apply the old limits
 * to fresh buckets. The failure is logged at ERROR with the number of skipped listeners.
 */
public abstract class AbstractReloadStrategy implements RuleReloadStrategy {

  /** Order used for cache invalidation listeners; runs first. */
  public static final int ORDER_CACHE_INVALIDATION = -100;

  /** Order used for bucket reset listeners; runs after the caches have been invalidated. */
  public static final int ORDER_BUCKET_RESET = 100;

  /** Default order applied by {@link #addListener(RuleReloadListener)}. */
  public static final int DEFAULT_ORDER = 0;

  protected final Logger log = LoggerFactory.getLogger(getClass());

  private final List<OrderedListener> listeners = new CopyOnWriteArrayList<>();
  private final AtomicBoolean running = new AtomicBoolean(false);

  /** The reload source for events generated by this strategy. */
  protected abstract ReloadSource getReloadSource();

  @Override
  public void start() {
    if (running.compareAndSet(false, true)) {
      log.info("Starting {} reload strategy", getClass().getSimpleName());
      doStart();
    } else {
      log.debug("{} reload strategy already running", getClass().getSimpleName());
    }
  }

  @Override
  public void stop() {
    if (running.compareAndSet(true, false)) {
      log.info("Stopping {} reload strategy", getClass().getSimpleName());
      doStop();
    } else {
      log.debug("{} reload strategy already stopped", getClass().getSimpleName());
    }
  }

  @Override
  public boolean isRunning() {
    return running.get();
  }

  @Override
  public void triggerReload(String ruleSetId) {
    Objects.requireNonNull(ruleSetId, "ruleSetId must not be null");
    log.debug("Triggering reload for ruleSetId: {}", ruleSetId);
    notifyListeners(RuleReloadEvent.forRuleSet(ruleSetId, ReloadSource.MANUAL));
  }

  @Override
  public void triggerReloadAll() {
    log.debug("Triggering full reload");
    notifyListeners(RuleReloadEvent.fullReload(ReloadSource.MANUAL));
  }

  @Override
  public void addListener(RuleReloadListener listener) {
    addListener(listener, DEFAULT_ORDER);
  }

  /**
   * Adds a listener that will be notified at the given order.
   *
   * @param listener the listener to add
   * @param order notification order; lower runs first (see {@link #ORDER_CACHE_INVALIDATION} and
   *     {@link #ORDER_BUCKET_RESET})
   */
  public void addListener(RuleReloadListener listener, int order) {
    Objects.requireNonNull(listener, "listener must not be null");
    listeners.add(new OrderedListener(listener, order));
    listeners.sort(Comparator.comparingInt(OrderedListener::getOrder));
    log.debug("Added reload listener: {} (order: {})", listener.getClass().getSimpleName(), order);
  }

  @Override
  public void removeListener(RuleReloadListener listener) {
    Objects.requireNonNull(listener, "listener must not be null");
    listeners.removeIf(entry -> entry.getListener().equals(listener));
    log.debug("Removed reload listener: {}", listener.getClass().getSimpleName());
  }

  /**
   * Notifies all registered listeners of a reload event, in ascending order.
   *
   * <p>Listeners sharing an order all run even if one of them fails; a failure then skips every
   * listener with a strictly higher order, so a failed cache invalidation never leads to a bucket
   * reset against stale rules.
   *
   * @param event the reload event
   */
  protected void notifyListeners(RuleReloadEvent event) {
    List<OrderedListener> snapshot = new ArrayList<>(listeners);
    if (snapshot.isEmpty()) {
      log.trace("No listeners registered, skipping notification");
      return;
    }

    log.debug("Notifying {} listeners of reload event: {}", snapshot.size(), event);

    int index = 0;
    while (index < snapshot.size()) {
      int order = snapshot.get(index).getOrder();
      List<String> failed = new ArrayList<>();

      // Run the whole group sharing this order before deciding whether to continue.
      while (index < snapshot.size() && snapshot.get(index).getOrder() == order) {
        OrderedListener entry = snapshot.get(index++);
        try {
          entry.getListener().onReload(event);
        } catch (Exception e) {
          failed.add(entry.getListener().getClass().getName());
          log.error(
              "Error notifying listener {} of reload event",
              entry.getListener().getClass().getName(),
              e);
        }
      }

      if (!failed.isEmpty() && index < snapshot.size()) {
        log.error(
            "Reload listeners {} failed at order {}; skipping the remaining {} listener(s) for "
                + "event {} to avoid acting on stale rules",
            failed,
            order,
            snapshot.size() - index,
            event);
        return;
      }
    }
  }

  /** Called when the strategy is started. Subclasses should implement their startup logic here. */
  protected abstract void doStart();

  /** Called when the strategy is stopped. Subclasses should implement their cleanup logic here. */
  protected abstract void doStop();

  /**
   * Returns the number of registered listeners.
   *
   * @return listener count
   */
  protected int getListenerCount() {
    return listeners.size();
  }

  /** A listener together with the order in which it should be notified. */
  private static final class OrderedListener {

    private final RuleReloadListener listener;
    private final int order;

    OrderedListener(RuleReloadListener listener, int order) {
      this.listener = listener;
      this.order = order;
    }

    RuleReloadListener getListener() {
      return listener;
    }

    int getOrder() {
      return order;
    }
  }
}
